---
- hosts: localhost
  name: web proxy firewall admin

  vars:
    whiteList:
      - customerName: "jSonar Inc."
        whitelist_cidrs:   "118.53.84.10/32"
      - customerName: "ABC Inc."
        whitelist_cidrs:   "28.114.26.103/32"
      - customerName: "XYX Inc."
        whitelist_cidrs:   "111.143.229.89/32"
#      - customerName: "123 Inc."
#        whitelist_cidrs:   "13.11.11.119/32"
#      - customerName: "AB5 Inc."
#        whitelist_cidrs:   "25.114.26.103/32"
#      - customerName: "XY5 Inc."
#        whitelist_cidrs:   "75.143.229.89/32"
#      - customerName: "125 Inc."
#        whitelist_cidrs:   "15.11.11.119/32"


  tasks:
#    - name: Query Master for customer Names: IPs
#      shell: mongo find() --> whiteList

    - name: Set rules for web proxy security group
      ec2_group:
        name: web_proxy_rules
        description: Whitelisted Customer IPs
        vpc_id: vpc-0c671ee0923501ef8 # web proxy VPC
        region: ca-central-1 # web proxy region
        purge_rules: false   # true by default!!!
        rules:

          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "10.10.10.0/24" # ssh from private subnet only
            rule_desc: private subnet

          - proto: tcp
            from_port: 443
            to_port: 443
            cidr_ip: "{{ item.whitelist_cidrs }}"
            rule_desc: "{{ item.customerName }}"

          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ item.whitelist_cidrs }}"
            rule_desc: "{{ item.customerName }}"

      with_items: "{{ whiteList }}"
#      register: output

#    - debug:
#        var: output

