---
# tasks file for mod_security_group

- name: Set rules for web proxy security group
  ec2_group:
    name:         "{{ name }}"
    description:  "{{ description }}" # required if group is already present
    region:       "{{ region }}"   # ca-central-1 - web proxy region
    vpc_id:       "{{ vpc_id }}"   # vpc-0c671ee0923501ef8 - web proxy VPC
    #group_id:    "{{ group_id }}" # or name but not both (name required if group already present)
    purge_rules:  false            # true by default!!!
    rules:

      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: "{{ item.whitelist_cidrs }}"
        rule_desc: "{{ item._id }}"

      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: "{{ item.whitelist_cidrs }}"
        rule_desc: "{{ item._id }}"

  with_items: "{{ whiteList }}"

# register: output

# - debug:
#     var: output

